### ISSUE TITLE
Inconsistency between username used for existence check and username at creation

### ISSUE THREAD

**Issue by ggoodman** [epicweb-dev/web-auth#1]
When checking if an existing user is in the database, it seems like the raw submitted username is used: https://github.com/epicweb-dev/web-auth/blob/fe1c9be4a71ec5f287a5ef1c88d30786b4ee01d1/exercises/03.password/03.solution.signup/app/routes/_auth%2B/signup.tsx#L51-L54

On the other hand, upon actually persisting the user, it seems like a transformed (lowercase) version of the same username is used: https://github.com/epicweb-dev/web-auth/blob/fe1c9be4a71ec5f287a5ef1c88d30786b4ee01d1/exercises/03.password/03.solution.signup/app/routes/_auth%2B/signup.tsx#L66-L78

If that is indeed the case, it would, at worst, allow clobbering an existing user (ie: account take-over) and at best, produce a unique index collision error instead of the intended `.addIssue()` trick. I'm not familiar with Prisma so not really sure where this would land.

**Comment by kentcdodds** [comment]
Hi @ggoodman! Good to hear from you! Thanks for giving this a look!

You're correct. This is a mistake. I'll get it fixed. Because the username has a unique constraint, the database won't allow a new user to be created with the same username as an existing user. But the error would be confusing. So yeah, I'll fix it up. Thanks again!

**Comment by kentcdodds** [comment]
I take it back. That won't happen because this is handled by the zod schema which will automatically lower-case the username for us: https://github.com/epicweb-dev/web-auth/blob/fe1c9be4a71ec5f287a5ef1c88d30786b4ee01d1/exercises/03.password/03.solution.signup/app/utils/user-validation.ts#L11

So we're good :)
